name: Pull-Request-Dev

on:
  pull_request:
    paths:
      - environments/dev/**

jobs:
  call-terraform:
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    uses: ./.github/workflows/terraform.yaml
    with:
      working-directory: environments/dev
      environment: dev
      terraform-version: 1.3.6
      terraform-state-key-prefix: environments/dev/
    secrets: inherit
