name: Pull-Request-Dev

on:
  pull_request:
    paths:
      - environments/dev/**

jobs:
  call-terraform-workflow:
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      terraform-version: 1.3.6
    secrets: inherit
